FROM quay.io/astronomer/astro-runtime:13.1.0

COPY ./dist/kedro_spaceflights_mlops-0.1-py3-none-any.whl /src/kedro_spaceflights_mlops-0.1-py3-none-any.whl

RUN pip install /src/kedro_spaceflights_mlops-0.1-py3-none-any.whl
