# ============================================================================
# AUTOGEN PPT GENERATION PARAMETERS
# ============================================================================

# User Query for PPT Generation
user_query: "Create a business presentation about quarterly sales performance with charts and key insights"
