tasks:
  - init: pip install -r spaceflights-completed/src/requirements.txt
    command: |
      cd spaceflights-jupyter 
      jupyter lab --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    name: jupyter

ports:
  - port: 8888